//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.Amazonia.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public long productId { get; set; }
        public string colour { get; set; }
        public string model { get; set; }
        public long enginePower { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
